# faster builds
git:
  depth: false
  submodules: false
sudo: false


language: java
jdk:
  - oraclejdk8
  - openjdk11
before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
# addons:
#   sonarcloud:
#     organization: "magefree"
#     token:
#       secure: SONAR_TOKEN
# script:
#    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
